import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const timesTen = localFont({
  src: [
    {
      path: "../../public/font/TimesTen.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-times-ten",
});

const helvetica = localFont({
  src: [
    {
      path: "../../public/font/Helvetica.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${timesTen.variable} ${helvetica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


